### ISSUE TITLE
RuntimeError: Cannot find the MXNet library

### ISSUE THREAD

**Issue by kaivu1999** [hpi-xnor/BMXNet-v2#4]
## Description
I am facing problem to install BMXNet.

## Environment info (Required)

CuDNN 7.1.4
Cuda 9.2
Nvcc V9.2.148

### Following python packages 
```
atomicwrites==1.3.0
attrs==19.1.0
certifi==2019.3.9
chardet==3.0.4
graphviz==0.8.4
idna==2.8
importlib-metadata==0.15
more-itertools==7.0.0
-e git+https://github.com/apache/incubator-mxnet@5fc4fc53df74f276aafa51208142e657e9cfe42d#egg=mxnet&subdirectory=python
numpy==1.16.4
pathlib2==2.3.3
pluggy==0.12.0
py==1.8.0
pytest==4.5.0
requests==2.22.0
six==1.12.0
urllib3==1.25.3
wcwidth==0.1.7
zipp==0.5.1
```

## Used the following for the mxnet build
```
cmake -j USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda USE_CUDNN=1 USE_MKLDNN=1 .
```

## Error Message:
```
@kaivu1999

>>> import mxnet as mx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kaivalya/ntu_second/mxnet/python/mxnet/__init__.py", line 24, in <module>
    from .context import Context, current_context, cpu, gpu, cpu_pinned
  File "/home/kaivalya/ntu_second/mxnet/python/mxnet/context.py", line 24, in <module>
    from .base import classproperty, with_metaclass, _MXClassPropertyMetaClass
  File "/home/kaivalya/ntu_second/mxnet/pythRuntimeError: Cannot find the MXNet libraryon/mxnet/base.py", line 213, in <module>
    _LIB = _load_lib()
  File>>> import mxnet as mx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kaivalya/ntu_second/mxnet/python/mxnet/__init__.py", line 29, in <module>
    from . import contrib
  File "/home/kaivalya/ntu_second/mxnet/python/mxnet/contrib/__init__.py", line 27, in <module>
    from . import autograd
  File "/home/kaivalya/ntu_second/mxnet/python/mxnet/contrib/autograd.py", line 29, in <module>
    from ..ndarray import NDArray, zeros_like, _GRAD_REQ_MAP
  File "/home/kaivalya/ntu_second/mxnet/python/mxnet/ndarray/__init__.py", line 26, in <module>
    from . import register
  File "/home/kaivalya/ntu_second/mxnet/python/mxnet/ndarray/register.py", line 177, in <module>
    from ._internal import _adamw_update, _mp_adamw_update
ImportError: cannot import name '_adamw_update' "/home/kaivalya/ntu_second/mxnet/python/mxnet/base.py", line 203, in _load_lib
    lib_path = libinfo.find_lib_path()
  File "/home/kaivalya/ntu_second/mxnet/python/mxnet/libinfo.py", line 74, in find_lib_path
    'List of candidates:\n' + str('\n'.join(dll_path)))
RuntimeError: Cannot find the MXNet library.
List of candidates:
/home/kaivalya/ntu_second/mxnet/libmxnet.so
/home/kaivalya/ntu_second/mxnet/python/mxnet/libmxnet.so
/home/kaivalya/ntu_second/mxnet/python/mxnet/../../lib/libmxnet.so
/home/kaivalya/ntu_second/mxnet/python/mxnet/../../build/libmxnet.so
../../../libmxnet.so

```

## What have you tried to solve it?
Well it seems the shared object file didnot get created. But I didnot face any problems in the executing the cmake command for Intel processors with GPU

1. Well I checked the PYTHONPATH
Here I would like to say that in the instructions it is written:
to add 
```
$ export LD_LIBRARY_PATH=<mxnet-root>/build/Release
$ export PYTHONPATH=<mxnet-root>/python
```

Where as we don't have build/Release in mxnet-root.
They were actually in the BMXNet v1 instructions. And while installing MXNet they has asked to build it for the cmake thing. But I could not see any reference to it in the new instructions of mxnet setup

2. Well I had install mxnet while installing BMXnet ( Version 1 without the Gluon support ) as well of course. And it had this shared object file. So I splecifically added the path accordingly in LD_LIBRARY_PATH which gave the following error.
```
>>> import mxnet as mx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kaivalya/ntu_second/mxnet/python/mxnet/__init__.py", line 29, in <module>
    from . import contrib
  File "/home/kaivalya/ntu_second/mxnet/python/mxnet/contrib/__init__.py", line 27, in <module>
    from . import autograd
  File "/home/kaivalya/ntu_second/mxnet/python/mxnet/contrib/autograd.py", line 29, in <module>
    from ..ndarray import NDArray, zeros_like, _GRAD_REQ_MAP
  File "/home/kaivalya/ntu_second/mxnet/python/mxnet/ndarray/__init__.py", line 26, in <module>
    from . import register
  File "/home/kaivalya/ntu_second/mxnet/python/mxnet/ndarray/register.py", line 177, in <module>
    from ._internal import _adamw_update, _mp_adamw_update
ImportError: cannot import name '_adamw_update'
```

Even after including the  both the paths I am getting the same here.

Can someone help me ? 
Thanking you in advance.

**Comment by yanghaojin** [comment]
Hi,
have you done this:
`cd <mxnet-root>/python
pip install -e .`

**Comment by Jopyth** [comment]
In which directory did you execute the cmake command? Did you create a build directory for cmake? And you did use make or ninja to build the .so file, right?

**Comment by kaivu1999** [comment]
@yanghaojin 
It was my bad.
I am closing this issue.
